"""empty message

Revision ID: 76527c630280
Revises: 
Create Date: 2023-12-16 11:12:59.768661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76527c630280'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
